import { Injectable } from '@nestjs/common';
import { PrismaService } from '../prisma/prisma.service';

@Injectable()
export class ChatService {
  constructor(private prisma: PrismaService) {}

  async saveMessage(meetingId: string, senderId: string, content: string, detectedLang: string, confidence: number) {
    return this.prisma.message.create({
      data: {
        meetingId,
        senderId,
        content,
        detectedLanguage: detectedLang,
        confidenceScore: confidence
      }
    });
  }

  async saveTranslation(messageId: string, targetLang: string, translatedText: string, timeMs: number, tokens: number, cacheHit: boolean) {
    const translation = await this.prisma.translationHistory.create({
      data: {
        messageId,
        targetLanguageId: targetLang, // We store the string code for simplicity based on DB constraints, normally it's relations
        translatedText,
        isAutoGenerated: true
      }
    });

    await this.prisma.chatAnalytics.create({
      data: {
        messageId,
        translationTimeMs: timeMs,
        aiTokensUsed: tokens,
        cacheHit
      }
    });

    return translation;
  }

  async getConversationContext(meetingId: string, limit = 5) {
    return this.prisma.message.findMany({
      where: { meetingId },
      orderBy: { createdAt: 'desc' },
      take: limit,
      include: { translations: true }
    });
  }
}
